lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser_common do
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
    plug(CodeStatsWeb.RememberMePlug)
    plug(CodeStatsWeb.SetSessionUserPlug)
    plug(CodeStatsWeb.ConsentPlug)
  end

  pipeline :browser_html do
    plug(:accepts, ["html"])
  end

  pipeline :browser_csv do
    plug(:accepts, ["csv"])
  end

  pipeline :browser_auth do
    plug(CodeStatsWeb.AuthRequiredPlug)
  end

  pipeline :browser_unauth do
    plug(CodeStatsWeb.AuthNotAllowedPlug)
  end

  pipeline :browser_changes_state do
    plug(:protect_from_forgery)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :api_machine_auth do
    plug(CodeStatsWeb.MachineAuthRequiredPlug)
  end

  scope "/" do
    pipe_through(:browser_html)
    pipe_through(:browser_common)

    get("/", CodeStatsWeb.PageController, :index)

    get("/api-docs", CodeStatsWeb.PageController, :api_docs)
    get("/tos", CodeStatsWeb.PageController, :terms)
    get("/plugins", CodeStatsWeb.PageController, :plugins)
    get("/changes", CodeStatsWeb.PageController, :changes)

    get("/aliases", CodeStatsWeb.AliasController, :list)

    get("/battle", CodeStatsWeb.BattleController, :battle)

    scope "/" do
      pipe_through(:browser_changes_state)
      pipe_through(:browser_unauth)

      get("/login", CodeStatsWeb.AuthController, :render_login)
      post("/login", CodeStatsWeb.AuthController, :login)
      get("/signup", CodeStatsWeb.AuthController, :render_signup)
      post("/signup", CodeStatsWeb.AuthController, :signup)
      get("/forgot-password", CodeStatsWeb.AuthController, :render_forgot)
      post("/forgot-password", CodeStatsWeb.AuthController, :forgot)
      get("/reset-password/:token", CodeStatsWeb.AuthController, :render_reset)
      put("/reset-password/:token", CodeStatsWeb.AuthController, :reset)
    end

    get("/logout", CodeStatsWeb.AuthController, :logout)

    get("/users/:username", CodeStatsWeb.ProfileController, :profile)
    forward("/profile-graph", Absinthe.Plug, schema: CodeStats.Profile.PublicSchema)
    forward("/profile-graphiql", Absinthe.Plug.GraphiQL, schema: CodeStats.Profile.PublicSchema)

    scope "/my", CodeStatsWeb do
      pipe_through(:browser_changes_state)
      pipe_through(:browser_auth)

      get("/profile", ProfileController, :my_profile)

      get("/preferences", PreferencesController, :edit)
      put("/preferences", PreferencesController, :do_edit)
      delete("/preferences", PreferencesController, :delete)

      get("/machines", MachineController, :list)
      post("/machines", MachineController, :add)
      get("/machines/:id", MachineController, :view_single)
      put("/machines/:id", MachineController, :edit)
      delete("/machines/:id", MachineController, :delete)
      post("/machines/:id/activate", MachineController, :activate)
      post("/machines/:id/deactivate", MachineController, :deactivate)
      post("/machines/:id/key", MachineController, :regen_machine_key)

      get("/consent", TermsController, :ask_consent)
      post("/consent", TermsController, :set_consent)
      delete("/consent-delete", TermsController, :delete_account)
    end
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_csv)
    pipe_through(:browser_common)
    pipe_through(:browser_auth)

    get("/my/pulses", PulseController, :list)
    get("/my/private", ProfileController, :export_private)
  end

  scope "/api", CodeStatsWeb do
    pipe_through(:api)

    get("/users/:username", ProfileController, :profile_api)

    scope "/my" do
      pipe_through(:api_machine_auth)

      post("/pulses", PulseController, :add)
    end
  end
end

lib/code_stats_web/views/layout_view.ex
defmodule CodeStatsWeb.LayoutView do
  use CodeStatsWeb, :view

  def get_title(conn) do
    site_name = get_conf(:site_name)

    if conn.assigns[:title] do
      "#{conn.assigns[:title]} – #{site_name}"
    else
      site_name
    end
  end

  @doc """
  Check if user is authenticated. If session is not fetched, return false.
  """
  def is_authed?(conn) do
    try do
      CodeStatsWeb.AuthUtils.is_authed?(conn)
    rescue
      _ -> false
    end
  end

  @doc """
  Get flash of given type if fetched, otherwise returns nil.
  """
  def get_flash(conn, type) do
    try do
      Phoenix.Controller.get_flash(conn, type)
    rescue
      _ -> nil
    end
  end
end

lib/code_stats_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <!-- Preload resources for MAXIMUM SPEED -->
    <link rel="preload" href="<%= Routes.static_path(@conn, "/css/frontend.css") %>" as="style">
    <link rel="preload" href="<%= Routes.static_path(@conn, "/js/frontend.js") %>" as="script">
    <link rel="preload" href="<%= Routes.static_path(@conn, "/assets/frontend/images/Logo.svg") %>" as="image">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Code::Stats is a free stats tracking service for programmers">
    <meta name="author" content="Mikko Ahlroth">

    <title><%= get_title(@conn) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/frontend.css") %>">

    <link rel="apple-touch-icon" sizes="180x180" href="/assets/frontend/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/frontend/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/frontend/favicon-16x16.png">
    <link rel="manifest" href="/assets/frontend/site.webmanifest">
    <link rel="mask-icon" href="/assets/frontend/safari-pinned-tab.svg" color="#3e4053">
    <link rel="shortcut icon" href="/assets/frontend/favicon.ico">
    <meta name="msapplication-TileColor" content="#603cba">
    <meta name="msapplication-config" content="/assets/frontend/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <%= if is_authed?(@conn) do %>
      <% username = get_current_user(@conn).username %>
      <%= tag(:meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", username)) %>
      <%= tag(:meta, name: "authed-username", content: username) %>
    <% end %>
  </head>

  <body>
    <header id="nav-stripe" class="stripe">
      <a id="header-logo" class="logo" href="<%= Routes.page_path(@conn, :index) %>">
        <img
         src="<%= Routes.static_path(@conn, "/assets/frontend/images/Logo.svg") %>"
         alt="<%= get_conf(:site_name) %> logo"
         title="<%= get_conf(:site_name) %>"
        />
      </a>

      <nav id="header-nav" role="navigation">
        <%= if is_authed?(@conn) do %>
          <a href="<%= Routes.profile_path(@conn, :my_profile) %>">Profile</a>
          <a href="<%= Routes.preferences_path(@conn, :edit) %>">Preferences</a>
          <a href="<%= Routes.machine_path(@conn, :list) %>">Machines</a>
          <a href="<%= Routes.auth_path(@conn, :logout) %>">Log out</a>
        <% else %>
          <a href="<%= Routes.auth_path(@conn, :render_login) %>">Log in</a>
          <a href="<%= Routes.auth_path(@conn, :render_signup) %>">Sign up</a>
        <% end %>
      </nav>
    </header>

    <section id="flash-stripe">
      <%= if flash = get_flash(@conn, :info) do %>
        <div class="stripe flash-stripe" role="alert">
          <%= flash %>
        </div>
      <% end %>
      <%= if flash = get_flash(@conn, :success) do %>
        <div class="stripe flash-stripe flash-success" role="alert">
          <%= flash %>
        </div>
      <% end %>
      <%= if flash = get_flash(@conn, :error) do %>
        <div class="stripe flash-stripe flash-error" role="alert">
          <%= flash %>
        </div>
      <% end %>

      <%= if get_conf(:beta_mode) do %>
        <section class="stripe flash-stripe" role="alert">
          <strong>Note!</strong>
          This instance is in beta mode. You can register as normal and use this instance for testing
          purposes, such as for developing a new editor plugin. The database may be reset at any time.
        </section>
      <% end %>

      <section id="ie-warning" class="stripe stripe-warning" role="alert">
        <strong>⚠️ Warning!</strong>
        It seems you are using Internet Explorer, which is an unsupported browser. This website uses technologies not supported
        by your browser and as such will probably not work. Please try using some recent browser, like
        <a href="https://www.google.com/chrome/browser/desktop/index.html" target="_blank">Google Chrome</a>,
        <a href="https://www.mozilla.org/en-US/firefox/new/" target="_blank">Mozilla Firefox</a>,
        or <a href="https://vivaldi.com/" target="_blank">Vivaldi</a>.
      </section>
    </section>

    <main>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer id="footer-stripe" class="stripe stripe-accent">
      <section>
        <h6 class="no-margin"><%= CodeStatsWeb.RequestTimePlug.calculate_time(@conn) %>, <%= inspect(self()) %></h6>
        <a href="<%= Routes.page_path(@conn, :changes)%>"><%= get_conf(:version) %>-<%= get_conf(:commit_hash) %></a>
        <a href="<%= Routes.page_path(@conn, :plugins) %>">Plugins</a>
        <a href="<%= Routes.page_path(@conn, :api_docs) %>">API docs</a>
        <a href="<%= Routes.page_path(@conn, :terms) %>">Legal</a>
      </section>

      <%= if not Enum.empty?(get_conf(:social_links)) do %>
        <section>
          <h6 class="no-margin">Contact us!</h6>
          <%= for {name, url} <- get_conf(:social_links) do %>
            <a href="<%= url %>"><%= name %></a>
          <% end %>
        </section>
      <% end %>

      <section>
        <p>
          Made with
          <a target="_blank" href="http://elixir-lang.org/">Elixir</a>,
          <a target="_blank" href="http://www.phoenixframework.org/">Phoenix</a>, and
          <a target="_blank" href="https://redom.js.org/">RE:DOM</a>.
        </p>
        <p class="no-margin">
          <small>
            <%= get_conf(:site_name) %> development sponsored by <a target="_blank" href="https://www.vincit.fi/en/">Vincit</a>, the passionate software company.
          </small>
        </p>
        <p class="no-margin">
          <small>
            Realtime monitoring provided by <a target="_blank" href="https://appsignal.com/">AppSignal</a>.
          </small>
        </p>
      </section>
    </footer>

    <div id="cookie-notice-container"></div>

    <!-- Mock moment.js until rollup-plugin-commonjs is fixed so we can ignore it instead of mocking -->
    <script type="text/javascript">
      window.moment = {};
    </script>
    <script async type="text/javascript" src="<%= Routes.static_path(@conn, "/js/frontend.js") %>"></script>
    <%= raw get_conf(:analytics_code) %>
  </body>
</html>

lib/code_stats_web/templates/layout/battle.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Code::Stats is a free stats tracking service for programmers">
    <meta name="author" content="Mikko Ahlroth">

    <title><%= get_conf(:site_name) %> Battle Mode</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/battle/css/battle.css") %>">

    <link rel="apple-touch-icon" sizes="57x57" href="/frontend/assets/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/frontend/assets/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/frontend/assets/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/frontend/assets/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/frontend/assets/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/frontend/assets/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/frontend/assets/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/frontend/assets/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/frontend/assets/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/frontend/assets/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/frontend/assets/manifest.json">
    <link rel="mask-icon" href="/frontend/assets/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/frontend/assets/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= if is_authed?(@conn) do %>
      <%= tag(:meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", get_current_user(@conn).username)) %>
    <% end %>
  </head>

  <body>
    <%= render @view_module, @view_template, assigns %>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/battle/js/battle.js") %>"></script>
    <%= raw get_conf(:analytics_code) %>
  </body>
</html>

lib/code_stats_web/templates/layout/email.text.eex
<%= get_conf(:site_name) %>
===========

<%= render @view_module, @view_template, assigns %>

-----------
This email was sent from <%= get_conf(:site_name) %> <<%= Routes.page_url(CodeStatsWeb.Endpoint, :index) %>>. If you do not wish to receive more emails, you can remove your email address in the preferences page of your account.

Please note that you cannot reply to this email.